name: Changesets CI
on: pull_request
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - id: diff
        name: Determine changed public packages from previous commit
        run: echo "::set-output name=hasChanges::$(pnpm list --filter "...[$(git rev-parse HEAD^1)]" --depth -1 --json | jq "any(.[] | select(.private != true) ; length > 0)")"
      - name: Get changed files in the changesets folder
        id: has-changesets
        uses: tj-actions/changed-files@v34
        with:
          files: |
            .changeset/**
      - name: Create missing changeset note if there are missing changesets
        if: steps.has-changesets.outputs.any_changed != 'true' && steps.diff.outputs.hasChanges == 'true'
        run: |
          echo "true" > missing-changeset.txt
      - name: Upload missing changeset artifact
        uses: actions/upload-artifact@v3
        if: steps.has-changesets.outputs.any_changed != 'true' && steps.diff.outputs.hasChanges == 'true'
        with:
          name: missing-changeset
          path: missing-changeset.txt
          if-no-files-found: error
          retention-days: 1
      - name: Attempt to create snapshots.
        run: pnpm changeset version --snapshot test-do-not-publish
