name: TypeScript SDK PR checks
on: pull_request
jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isTypescriptSDK: ${{ contains(fromJson(steps.pnpm.outputs.packages), '@mysten/sui.js') || steps.diff.outputs.isRust }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect Changes (pnpm)
        uses: "./.github/actions/pnpm-diffs"
        id: pnpm
      - name: Detect Changes (diff)
        uses: "./.github/actions/diffs"
        id: diff

  client_checks:
    name: Test & Build
    needs: diff
    if: needs.diff.outputs.isTypescriptSDK == 'true'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm sdk test:unit
      - name: Build
        run: pnpm sdk build
  end_to_end:
    name: End-to-end tests
    needs: diff
    if: needs.diff.outputs.isTypescriptSDK == 'true'
    runs-on: [ubuntu-ghcloud]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - run: cargo build --bin sui-test-validator --bin sui --profile dev
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run e2e tests
        run: pnpm dlx concurrently --kill-others --success command-1 'cargo run --bin sui-test-validator' 'pnpm sdk test:e2e'
