[package]
name = "sui-rosetta"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
axum = "0.5.13"
axum-core = "0.2.7"
anyhow = { version = "1.0.64", features = ["backtrace"] }
tracing = "0.1.36"
serde = "1.0.143"
serde_json = { version = "1.0.83", features = ["preserve_order"] }
tower = { version = "0.4.12", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.3.4", features = ["cors"] }
tokio = "1.20.1"
once_cell = "1.16"
serde_with = "2.0.1"
signature = "1.6.0"
bcs = "0.1.4"
hyper = "0.14.20"
strum = "0.24.1"
strum_macros = "0.24.3"
async-trait = "0.1.57"
clap = { version = "3.2.17", features = ["derive"] }

fastcrypto.workspace = true

sui-types = { path = "../sui-types" }
sui-core = { path = "../sui-core" }
sui-node = { path = "../sui-node" }
sui-config = { path = "../sui-config" }
sui-keys = { path = "../sui-keys" }
sui-metrics = { path = "../sui-metrics" }

move-core-types.workspace = true

telemetry-subscribers.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
sui-sdk = { path = "../sui-sdk" }
sui-framework = { path = "../sui-framework" }
sui-framework-build = { path = "../sui-framework-build" }
test-utils = { path = "../test-utils" }
tempfile = "3.3.0"
rand = "0.8.5"
