[package]
name = "narwhal-executor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false

[dependencies]
async-trait = "0.1.57"
bincode = "1.3.3"
bytes = "1.2.1"
config = { path = "../config", package = "narwhal-config" }
consensus = { path = "../consensus", package = "narwhal-consensus" }
fastcrypto.workspace = true
futures = "0.3.24"
multiaddr = "0.16.0"
primary = { path = "../primary", package = "narwhal-primary" }
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.35"
tokio = { version = "1.20.1", features = ["sync"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = "0.8.2"
tracing = "0.1.36"
prometheus = "0.13.3"
backoff = { version = "0.4.0", features = ["tokio"] }
storage = { path = "../storage", package = "narwhal-storage" }
itertools = "0.10.5"

types = { path = "../types", package = "narwhal-types" }
network = { path = "../network", package = "narwhal-network" }
crypto = { path = "../crypto", package = "narwhal-crypto" }
anyhow = "1.0.65"
match_opt = "0.1.2"
rand = "0.8.5"
mockall = "0.11.2"

sui-metrics = { path = "../../crates/sui-metrics" }
store = { path = "../../crates/typed-store", package = "typed-store" }
telemetry-subscribers = { path = "../../crates/telemetry-subscribers"}

workspace-hack.workspace = true

[dev-dependencies]
indexmap = { version = "1.9.1", features = ["serde"] }
tempfile = "3.3.0"
primary = { path = "../primary", package = "narwhal-primary" }
node = { path = "../node", package = "narwhal-node" }
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
types = { path = "../types", package = "narwhal-types" }