[package]
name = "sui-tool"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
clap = { version = "3.2.17", features = ["derive"] }

textwrap = "0.15"
futures = "0.3.23"
rocksdb = "0.19.0"
tempfile = "3.3.0"
narwhal-executor = { path = "../../narwhal/executor" }
serde_with = { version = "2.0.1", features = ["hex"] }
sui-storage = { path = "../sui-storage" }
strum_macros = "^0.24"
strum = "0.24.1"
serde = { version = "1.0.144", features = ["derive"] }
eyre = "0.6.8"

sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }
sui-network = { path = "../sui-network" }
telemetry-subscribers.workspace = true

colored = "2.0.0"
workspace-hack.workspace = true
