[package]
name = "sui-network"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anemo.workspace = true
async-trait = "0.1.57"
serde = { version = "1.0.144", features = ["derive"] }
tonic = "0.8"

sui-types = { path = "../sui-types" }
sui-config = { path = "../sui-config" }

mysten-network.workspace = true
workspace-hack.workspace = true
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.37"
futures = "0.3.24"
multiaddr = "0.16.0"
tap = "1.0.1"
rand = "0.8.5"
anyhow = "1.0.65"

[build-dependencies]
anemo-build.workspace = true
tonic-build = { version = "0.8.2", features = [ "transport" ] }

[dev-dependencies]
telemetry-subscribers.workspace = true
tokio = { version = "1.17.0", features = ["test-util"] }
