[package]
name = "sui-gateway"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
async-trait = "0.1.57"
serde = { version = "1.0.144", features = ["derive"] }
tracing = "0.1.36"
tokio = { version = "1.20.1", features = ["full"] }
futures = "0.3.23"
prometheus = "0.13.3"
clap = { version = "3.2.17", features = ["derive"] }

sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
sui-json-rpc = { path = "../sui-json-rpc" }
sui-json-rpc-types= { path = "../sui-json-rpc-types" }
sui-node = { path = "../sui-node" }
sui-keys = { path = "../sui-keys" }
telemetry-subscribers.workspace = true

workspace-hack.workspace = true

[dev-dependencies]
test-utils = { path = "../test-utils" }
sui-framework-build = { path = "../sui-framework-build" }
sui-sdk = { path = "../sui-sdk" }

[[bin]]
name = "rpc-server"
path = "src/main.rs"
