---
version: "3.9"
services:
  rosetta-online:
    image: mysten/sui-rosetta-local
    ports:
      - "9002:9002"
      - "9000:9000"
    expose:
      - "9002"
      - "9000"
    working_dir: /sui/localnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/sui-rosetta generate-rosetta-cli-config &
        /usr/local/bin/sui start &> /sui/sui.log &
        /usr/local/bin/sui-rosetta start-online-server
    stdin_open: true
    tty: true
  rosetta-offline:
    image: mysten/sui-rosetta-local
    ports:
      - "9003:9003"
    expose:
      - "9003"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/sui-rosetta start-offline-server
    stdin_open: true
    tty: true