[package]
name = "test-utils"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
futures = "0.3.23"
tempfile = "3.3.0"
tracing = "0.1.36"
signature = "1.6.0"
bcs = "0.1.4"
jsonrpsee-http-client = "0.15.1"
jsonrpsee = { version = "0.15.1", features = ["full"] }
prometheus = "0.13.3"
tokio = { version = "1.20.1", features = ["full", "tracing", "test-util"] }
serde_json = "1.0.83"
rand = "0.8.5"
sui = { path = "../sui" }
sui-adapter = { path = "../sui-adapter" }
sui-config = { path = "../sui-config" }
sui-core = { path = "../sui-core" }
sui-framework = { path = "../sui-framework" }
sui-framework-build = { path = "../sui-framework-build" }
sui-json-rpc = { path = "../sui-json-rpc" }
sui-json-rpc-types= { path = "../sui-json-rpc-types" }
sui-node = { path = "../sui-node" }
sui-swarm = { path = "../sui-swarm" }
sui-types = { path = "../sui-types" }
sui-keys = { path = "../sui-keys" }
sui-sdk = { path = "../sui-sdk" }
once_cell = "1.16"
multiaddr = "0.16.0"

mysten-network.workspace = true

move-core-types.workspace = true
workspace-hack.workspace = true

[target.'cfg(msim)'.dependencies]
sui-simulator = { path = "../sui-simulator" }
