[package]
name = "sui-core"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
rocksdb = "0.19.0"
anyhow = { version = "1.0.64", features = ["backtrace"] }
bcs = "0.1.4"
chrono = "0.4.0"
futures = "0.3.23"
bytes = "1.2.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.83"
serde_with = "2.0.1"
tokio = { version = "1.20.1", features = ["full", "tracing", "test-util"] }
tokio-stream = { version = "0.1.8", features = ["sync", "net"] }
parking_lot = "0.12.1"
async-trait = "0.1.57"
tempfile = "3.3.0"
itertools = "0.10.4"
tracing = "0.1.36"
signature = "1.6.0"
bincode = "1.3.3"
multiaddr = "0.16.0"
prometheus = "0.13.3"
arc-swap = "1.5.1"
tokio-retry = "0.3"
scopeguard = "1.1"
once_cell = "1.16"
tap = "1.0"
either = "1.8.0"
rand = "0.8.5"
sui-adapter = { path = "../sui-adapter" }
sui-framework = { path = "../sui-framework" }
sui-network = { path = "../sui-network" }
sui-types = { path = "../sui-types" }
sui-storage = { path = "../sui-storage" }
sui-config = { path = "../sui-config" }
sui-json = { path = "../sui-json" }
sui-json-rpc-types = { path = "../sui-json-rpc-types" }
sui-metrics = { path = "../sui-metrics" }

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
move-vm-runtime.workspace = true

narwhal-config = { path = "../../narwhal/config" }
narwhal-consensus = { path = "../../narwhal/consensus" }
narwhal-executor = { path = "../../narwhal/executor" }
narwhal-node = { path = "../../narwhal/node" }
narwhal-types = { path = "../../narwhal/types" }
telemetry-subscribers.workspace = true
typed-store.workspace = true
typed-store-derive.workspace = true
mysten-network.workspace = true

fastcrypto.workspace = true
workspace-hack.workspace = true
thiserror = "1.0.34"
eyre = "0.6.8"
num_cpus = "1.13.1"

sui-simulator = { path = "../sui-simulator" }
sui-macros = { path = "../sui-macros" }

[dev-dependencies]
clap = { version = "3.2.17", features = ["derive"] }

serde-reflection = "0.3.6"
serde_yaml = "0.8.26"
pretty_assertions = "1.2.1"

sui-framework-build = { path = "../sui-framework-build" }
sui-macros = { path = "../sui-macros" }

test-fuzz = "3.0.4"
test-utils = { path = "../test-utils" }

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false
