[package]
name = "suite"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
assert_approx_eq = "1.1.0"
rand = "0.8.4"
engine = { path = "../engine" }
proc = { path = "../proc" }
criterion = "0.3"

[[bench]]
name = "engine_bench"
harness = false

[[bench]]
name = "proc_bench"
harness = false
