[package]
name = "gdex-tests"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
assert_approx_eq = "1.1.0"
rand = "0.7.0"
criterion = "0.3.4"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"
bcs = "0.1.2"
rocksdb = "0.18.0"
tokio = { version = "1", features = ["full"] }


gdex-engine = { path = "../engine" }
gdex-controller = { path = "../controller" }
gdex-types = { path = "../types", features=["testing"] }
gdex-workspace-hack = { path = "../workspace-hack" }

[[bench]]
name = "engine"
harness = false