[package]
name = "suite"
version = "0.1.0"
authors = []
edition = "2018"
features = ["batch"]

[dependencies]
assert_approx_eq = "1.1.0"
rand = "0.7.0"
criterion = "0.3.4"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"
bcs = "0.1.2"
rocksdb = "0.18.0"
core = { path = "../core" }
gdex-crypto-derive = { path = "../crypto-derive", version = "0.0.2" }
gdex-crypto = { path = "../crypto", features = ["batch"] }
diem-workspace-hack = { path = "../workspace-hack" }
engine = { path = "../engine" }
proc = { path = "../proc" }
types = { path = "../types" }

[[bench]]
name = "orderbook_bench"
harness = false

[[bench]]
name = "ed25519"
harness = false

[[bench]]
name = "hash"
harness = false

[features]
batch = []
