[package]
name = "gdex-tests"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
assert_approx_eq = "1.1.0"
bcs = "0.1.2"
bincode = "1.3.3"
criterion = { version = "0.3.5", features = ["async_tokio"] }
narwhal-crypto = { git = "https://github.com/MystenLabs/narwhal", rev = "259a37b487570763575e6b28f8b8057b16b3e916", package = "crypto", features=["copy_key"]}
narwhal-types = { git = "https://github.com/MystenLabs/narwhal", rev = "259a37b487570763575e6b28f8b8057b16b3e916", package = "types" }
rand = "0.7.0"
rocksdb = "0.18.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.3.0"
tokio = { version = "1", features = ["full"] }

gdex-core = { path = "../core" }
gdex-engine = { path = "../engine" }
gdex-controller = { path = "../controller" }
gdex-types = { path = "../types", features=["testing"] }
gdex-workspace-hack = { path = "../workspace-hack" }

[[bench]]
name = "engine"
harness = false

[[bench]]
name = "concurrency"
harness = false