[package]
name = "sui-cluster-test"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
futures = "0.3.24"
serde_json = "1.0.83"
tempfile = "3.3.0"
tokio = { version = "1.20.1", features = ["full"] }
jsonrpsee = { version = "0.15.1", features = ["full"] }
tracing = { version = "0.1.36", features = ["log"] }
clap = { version = "3.1.14", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
async-trait = "0.1.57"
anyhow = { version = "1.0.64", features = ["backtrace"] }
bcs = "0.1.4"
uuid = {version = "1.1.2", features = [ "v4", "fast-rng"]}
prometheus = "0.13.3"
fastcrypto = { workspace = true }

sui-faucet = { path = "../sui-faucet" }
sui-swarm = { path = "../sui-swarm" }
sui = { path = "../sui" }
sui-json-rpc-types= { path = "../sui-json-rpc-types" }
sui-sdk = { path = "../sui-sdk" }
sui-keys = { path = "../sui-keys" }
sui-types = { path = "../sui-types" }
sui-core = { path = "../sui-core" }
sui-json = { path = "../sui-json" }
sui-config = { path = "../sui-config" }
sui-transaction-builder = { path = "../sui-transaction-builder" }
telemetry-subscribers.workspace = true

test-utils = { path = "../test-utils" }
workspace-hack.workspace = true
move-core-types.workspace = true
