[package]
name = "gdex-types"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
blake2 = "0.9"
narwhal-crypto = { git = "https://github.com/MystenLabs/narwhal", rev = "259a37b487570763575e6b28f8b8057b16b3e916", package = "crypto", features=["copy_key"]}
narwhal-types = { git = "https://github.com/MystenLabs/narwhal", rev = "259a37b487570763575e6b28f8b8057b16b3e916", package = "types" }
rand = { version = "0.7.3" }
serde = { version = "1.0.139", features = ["derive"] }
thiserror = "1.0.31"

[features]
testing = []