[package]
name = "types"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
bcs = "0.1.2"
serde = { version = "1.0.124", features = ["derive"] }
diem-crypto = { path = "../crypto" }
diem-crypto-derive = { path = "../crypto-derive", version = "0.0.2" }

[features]
batch = []
