[package]
name = "sui-faucet"
version.workspace = true
edition = "2021"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
async-trait = "0.1.57"
axum = "0.5.16"
clap = { version = "3.2.17", features = ["derive"] }
thiserror = "1.0.34"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
serde = { version = "1.0.144", features = ["derive"] }
tower = { version = "0.4.12", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.3.4", features = ["cors"] }
http = { version = "0.2.8" }
futures = "0.3.23"
uuid = {version = "1.1.2", features = [ "v4", "fast-rng"]}
prometheus = "0.13.3"
scopeguard = "1.1"
tap = "1.0"

sui = { path = "../sui" }
sui-node = { path = "../sui-node" }
sui-json-rpc-types= { path = "../sui-json-rpc-types" }
sui-types = { path = "../sui-types" }
sui-config = { path = "../sui-config" }
sui-keys = { path = "../sui-keys" }
sui-metrics = { path = "../../crates/sui-metrics" }
telemetry-subscribers.workspace = true

workspace-hack.workspace = true

[dev-dependencies]
test-utils = { path = "../test-utils" }

[[bin]]
name = "sui-faucet"
path = "src/main.rs"
