[package]
name = "sui-transaction-builder"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.64"
async-trait = "0.1.57"
futures = "0.3.23"
bcs = "0.1.4"

sui-json-rpc-types= { path = "../sui-json-rpc-types" }
sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
sui-adapter =  { path = "../sui-adapter" }

move-core-types.workspace = true

workspace-hack.workspace = true
