[package]
name = "narwhal-network"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.57"
backoff = { version = "0.4.0", features = ["tokio"] }
bytes = "1.2.1"
fastcrypto.workspace = true
futures = "0.3.24"
multiaddr = "0.16.0"
prometheus = "0.13.3"
rand = { version = "0.8.5", features = ["small_rng"] }
thiserror = "1.0.35"
tokio = { version = "1.20.1", features = ["rt", "net", "sync", "macros", "time"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = { version = "0.8.2", features = ["tls"] }
tracing = "0.1.36"
types = { path = "../types", package = "narwhal-types" }
crypto = { path = "../crypto", package = "narwhal-crypto" }
sui-metrics = { path = "../../crates/sui-metrics" }

serde = "1.0.144"
workspace-hack.workspace = true
eyre = "0.6.8"

anemo.workspace = true
anemo-tower.workspace = true
anyhow = "1.0.65"
axum = "0.5.16"
axum-server = "0.4.2"
tower = "0.4.13"

[dev-dependencies]
bincode = "1.3.3"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
