[package]
name = "core"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
bcs = "0.1.2"
futures = "0.3"
gdex-crypto-derive = { path = "../crypto-derive", version = "0.0.2" }
gdex-crypto = { path = "../crypto", features = ["batch"] }
diem-workspace-hack = { path = "../workspace-hack" }
rand = "0.7.0"
serde = { version = "1.0.124", features = ["derive"] }
types = { path = "../types" }

[features]
batch = []
