../target/release/gdex init-genesis --path $PWD
../target/release/gdex add-validator-genesis --path $PWD --name validator-0 --balance 200000000 --stake 1000000 --key-file validator-0.key --network-address /dns/localhost/tcp/61228/http --narwhal-primary-to-primary /dns/localhost/tcp/61330/http --narwhal-worker-to-primary /dns/localhost/tcp/61432/http --narwhal-primary-to-worker /dns/localhost/tcp/61534/http --narwhal-worker-to-worker /dns/localhost/tcp/61636/http --narwhal-consensus-address /dns/localhost/tcp/61738/http
../target/release/gdex add-validator-genesis --path $PWD --name validator-1 --balance 300000000 --stake 2000000 --key-file validator-1.key --network-address /dns/localhost/tcp/62340/http --narwhal-primary-to-primary /dns/localhost/tcp/62442/http --narwhal-worker-to-primary /dns/localhost/tcp/62544/http --narwhal-primary-to-worker /dns/localhost/tcp/62646/http --narwhal-worker-to-worker /dns/localhost/tcp/62748/http --narwhal-consensus-address /dns/localhost/tcp/62850/http
../target/release/gdex add-validator-genesis --path $PWD --name validator-2 --balance 400000000 --stake 3000000 --key-file validator-2.key --network-address /dns/localhost/tcp/63452/http --narwhal-primary-to-primary /dns/localhost/tcp/63454/http --narwhal-worker-to-primary /dns/localhost/tcp/63556/http --narwhal-primary-to-worker /dns/localhost/tcp/63658/http --narwhal-worker-to-worker /dns/localhost/tcp/63760/http --narwhal-consensus-address /dns/localhost/tcp/63862/http
../target/release/gdex add-validator-genesis --path $PWD --name validator-3 --balance 500000000 --stake 4000000 --key-file validator-3.key --network-address /dns/localhost/tcp/64564/http --narwhal-primary-to-primary /dns/localhost/tcp/64366/http --narwhal-worker-to-primary /dns/localhost/tcp/64468/http --narwhal-primary-to-worker /dns/localhost/tcp/64570/http --narwhal-worker-to-worker /dns/localhost/tcp/64672/http --narwhal-consensus-address /dns/localhost/tcp/64774/http
../target/release/gdex add-validator-genesis --path $PWD --name validator-4 --balance 600000000 --stake 5000000 --key-file validator-4.key --network-address /dns/localhost/tcp/64764/http --narwhal-primary-to-primary /dns/localhost/tcp/64566/http --narwhal-worker-to-primary /dns/localhost/tcp/64668/http --narwhal-primary-to-worker /dns/localhost/tcp/64770/http --narwhal-worker-to-worker /dns/localhost/tcp/64872/http --narwhal-consensus-address /dns/localhost/tcp/64974/http
../target/release/gdex add-controllers-genesis --path $PWD
../target/release/gdex build-genesis --path $PWD
../target/release/gdex verify-and-sign-genesis --path $PWD --key-file validator-0.key
../target/release/gdex verify-and-sign-genesis --path $PWD --key-file validator-1.key
../target/release/gdex verify-and-sign-genesis --path $PWD --key-file validator-2.key
../target/release/gdex verify-and-sign-genesis --path $PWD --key-file validator-3.key
../target/release/gdex verify-and-sign-genesis --path $PWD --key-file validator-4.key
../target/release/gdex finalize-genesis --path $PWD