[package]
name = "proc"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
assert_approx_eq = "1.1.0"
core = { path = "../core" }
rand = "0.8.4"
criterion = "0.3.4"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"
bcs = "0.1.2"
engine = { path = "../engine" }
diem-crypto-derive = { path = "../crypto-derive", version = "0.0.2" }
diem-crypto = { path = "../crypto" }
diem-workspace-hack = { path = "../workspace-hack" }
types = { path = "../types" }