[package]
name = "gdex-node"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
clap = "2.34"
futures = "0.3.21"
telemetry-subscribers = { git = "https://github.com/MystenLabs/mysten-infra", rev = "a4c2cae59d823533061a5d8fe28771629819c43f" }
tokio = { version = "1.20.1", features = ["full", "tracing", "test-util"] }
tracing = "0.1.36"

gdex-core = { path = "../core" }