[package]
name = "sui-benchmark"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.57"
rayon = "1.5.3"
anyhow = { version = "1.0.64", features = ["backtrace"] }
futures = "0.3.23"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.83"
tempfile = "3.3.0"
tokio = { version = "1.20.1", features = ["full"] }
strum = "0.24.1"
strum_macros = "0.24.3"
num_cpus = "1.13.1"
rocksdb = "0.19.0"
serde_with = { version = "2.0.1", features = ["hex"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["time", "registry", "env-filter"] }
clap = { version = "3.1.17", features = ["derive"] }
prometheus = "0.13.3"
multiaddr = "0.16.0"
rand = "0.8.5"
base64 = "0.13.0"
rand_distr = "0.4.3"
indicatif = "0.17.0"
duration-str = "0.4.0"
hdrhistogram = "7.5.1"
comfy-table = "6.1.0"
bcs = "0.1.4"
tokio-util = "0.7.4"
sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-network = { path = "../sui-network" }
sui-types = { path = "../sui-types" }
sui-sdk = { path = "../sui-sdk" }
sui-keys = { path = "../sui-keys" }
sui-node = { path = "../sui-node" }
sui-json-rpc-types = { path = "../sui-json-rpc-types" }
telemetry-subscribers.workspace = true

move-core-types.workspace = true
narwhal-node = { path = "../../narwhal/node" }
workspace-hack.workspace = true
test-utils = { path = "../test-utils" }

[target.'cfg(msim)'.dependencies]
sui-macros = { path = "../sui-macros" }
sui-simulator = { path = "../sui-simulator" }

[features]
benchmark = ["narwhal-node/benchmark"]
