[package]
name = "sui-metrics"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
workspace-hack.workspace = true
tracing = "0.1"
scopeguard = "1"
prometheus = "0.13"
once_cell = "1"
tokio = "1"
tap = "1.0"
