name: Detect Changes in Pnpm Workspace
description: Defines variables indicating the parts of the pnpm workspace have changed
outputs:
  packages:
    description: A list of packages that have changed.
    value: ${{ steps.changes.outputs.packages }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - id: changes
      name: Detect changes
      shell: bash
      run: echo "::set-output name=packages::$(pnpm list --filter "...[origin/main]" --depth -1 --json | jq -c "[.[] | .name]")"
    - name: Print changes for easy debugging
      shell: bash
      run: echo ${{ steps.changes.outputs.packages }}
