[package]
name = "sui-types"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
bincode = "1.3.3"
bcs = "0.1.4"
byteorder = "1.4.3"
itertools = "0.10.5"
once_cell = "1.16"
rand = "0.8.5"
serde = { version = "1.0.144", features = ["derive"] }
curve25519-dalek = { version = "3", default-features = false, features = ["serde", "u64_backend"] }
serde-name = "0.2.1"
sha2 = "0.9.9"
thiserror = "1.0.34"
tracing = "0.1"
serde_bytes = "0.11.7"
serde_json = "1.0.83"
serde_with = "2.0.1"
serde_repr = "0.1"
signature = "1.6.0"
static_assertions = "1.1.0"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
zeroize = "1.5.7"
schemars ="0.8.10"
tonic = "0.8"
strum = "^0.24"
strum_macros = "^0.24"
roaring = "0.10.1"
enum_dispatch = "^0.3"
eyre = "0.6.8"

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-vm-types.workspace = true

narwhal-executor = { path = "../../narwhal/executor" }

fastcrypto = { workspace = true, features = ["copy_key"] }

sui-cost-tables = { path = "../sui-cost-tables"}
typed-store.workspace = true
name-variant = { path = "../../crates/name-variant" }

workspace-hack.workspace = true
proptest = "1.0.0"

[dev-dependencies]
bincode = "1.3.3"
test-utils = { path = "../test-utils" }
