name: Explorer Client PR checks
on: pull_request
jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isClient: ${{ contains(fromJson(steps.pnpm.outputs.packages), 'sui-explorer') || steps.diff.outputs.isRust }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect Changes (pnpm)
        uses: "./.github/actions/pnpm-diffs"
        id: pnpm
      - name: Detect Changes (diff)
        uses: "./.github/actions/diffs"
        id: diff
  client_checks:
    name: Lint, Test & Build
    needs: diff
    if: needs.diff.outputs.isClient == 'true'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm explorer lint
      - name: Unit Tests
        run: pnpm explorer test:unit
      - name: Build
        run: pnpm explorer build
  end_to_end_static:
    name: End-to-end tests (Static)
    needs: diff
    if: needs.diff.outputs.isClient == 'true'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Cypress
        run: pnpm explorer exec cypress install
      - name: Run e2e tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: pnpm dev:static
          working-directory: ./apps/explorer
          spec: cypress/e2e/static/*
  end_to_end_localnet:
    name: End-to-end tests (Localnet)
    needs: diff
    if: needs.diff.outputs.isClient == 'true'
    runs-on: [ubuntu-ghcloud]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - run: cargo build --bin sui-test-validator --profile dev
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Cypress
        run: pnpm explorer exec cypress install
      - name: Run e2e tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: pnpm dlx concurrently --kill-others 'cargo run --bin sui-test-validator' 'pnpm dev'
          working-directory: ./apps/explorer
          spec: cypress/e2e/localnet/*
          # Wait on faucet and explorer:
          wait-on: "http://localhost:3000, http://localhost:9123"
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
