name: Lines

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install tokei
      run: cargo install tokei --features all
    - name: Run tokei
      run: tokei
    - name: Run tokei no crypto
      run: tokei --exclude crypto crypto-derive