name: Pnpm Audit
on: pull_request
jobs:
  audit:
    name: pnpm audit
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Run audit
        run: pnpm audit --prod --audit-level moderate
