name: Wallet Extension PR Checks
on: pull_request
jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      isWalletExt: ${{ contains(fromJson(steps.pnpm.outputs.packages), 'sui-wallet') || steps.diff.outputs.isRust }}
      isSrcChange: ${{ contains(fromJson(steps.pnpm.outputs.packages), 'sui-wallet') }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect Changes (pnpm)
        uses: "./.github/actions/pnpm-diffs"
        id: pnpm
      - name: Detect Changes (diff)
        uses: "./.github/actions/diffs"
        id: diff

  run_checks:
    name: Lint, Test & Build
    needs: diff
    if: needs.diff.outputs.isWalletExt == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm wallet lint
      - name: Test
        run: pnpm wallet test
      - name: Build
        run: pnpm wallet build:prod
      - name: Package
        run: pnpm wallet pack:zip
      - uses: actions/upload-artifact@v3
        if: ${{ needs.diff.outputs.isSrcChange == 'true' }}
        with:
          name: wallet-extension
          path: apps/wallet/web-ext-artifacts/*
          if-no-files-found: error
          retention-days: 7
