name: Wallet Extension PR Comment

# NOTE: This workflow run indirection is used to securely comment on PRs when
# wallet builds are completed.
on:
  workflow_run:
    workflows: ["Wallet Extension PR Checks"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Get workflow run information
        uses: potiuk/get-workflow-origin@v1_1
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: "Download artifact"
        uses: actions/github-script@v6
        id: get-artifact
        with:
          result-encoding: string
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });

            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "wallet-extension"
            })[0];

            if (!matchArtifact) {
              return '';
            }

            return `https://github.com/MystenLabs/sui/actions/runs/${context.payload.workflow_run.id}#artifacts`;

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: steps.get-artifact.outputs.result != ''
        with:
          pr_number: ${{ steps.source-run-info.outputs.pullRequestNumber }}
          comment_includes: "💳 Wallet Extension"
          message: |
            💳 Wallet Extension has been built, you can download the packaged extension here: ${{steps.get-artifact.outputs.result}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
